/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.examples.http.client;

import io.apimatic.coreinterfaces.http.Callback;

/**
 * Callback to be called before and after the HTTP call for an endpoint is made.
 */
public interface HttpCallback extends Callback {

}